<?xml version="1.0" encoding="utf-8"?><Database Name="forummembership" Class="ForumMembershipModelsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\forummembership.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="forummembershipConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CategoryMembers" Member="CategoryMembers">
    <Type Name="CategoryMember">
      <Column Name="IDCategoryMember" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDMember" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IDCategory" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Member_CategoryMember" Member="Member" ThisKey="IDMember" OtherKey="IDMember" Type="Member" IsForeignKey="true" />
      <Association Name="Category_CategoryMember" Member="Category" ThisKey="IDCategory" OtherKey="IDCategory" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Members" Member="Members">
    <Type Name="Member">
      <Column Name="IDMember" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Member_CategoryMember" Member="CategoryMembers" ThisKey="IDMember" OtherKey="IDMember" Type="CategoryMember" />
      <Association Name="Member_Post" Member="Posts" ThisKey="IDMember" OtherKey="IDMember" Type="Post" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryPosts" Member="CategoryPosts">
    <Type Name="CategoryPost">
      <Column Name="IDCategoryPost" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDCategory" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IDPost" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Post_CategoryPost" Member="Post" ThisKey="IDPost" OtherKey="IDPost" Type="Post" IsForeignKey="true" />
      <Association Name="Category_CategoryPost" Member="Category" ThisKey="IDCategory" OtherKey="IDCategory" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Posts" Member="Posts">
    <Type Name="Post">
      <Column Name="IDPost" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDCategory" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IDMember" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Post_CategoryPost" Member="CategoryPosts" ThisKey="IDPost" OtherKey="IDPost" Type="CategoryPost" />
      <Association Name="Member_Post" Member="Member" ThisKey="IDMember" OtherKey="IDMember" Type="Member" IsForeignKey="true" />
      <Association Name="Category_Post" Member="Category" ThisKey="IDCategory" OtherKey="IDCategory" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="IDCategory" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ImageURL" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Category_CategoryMember" Member="CategoryMembers" ThisKey="IDCategory" OtherKey="IDCategory" Type="CategoryMember" />
      <Association Name="Category_CategoryPost" Member="CategoryPosts" ThisKey="IDCategory" OtherKey="IDCategory" Type="CategoryPost" />
      <Association Name="Category_Post" Member="Posts" ThisKey="IDCategory" OtherKey="IDCategory" Type="Post" />
    </Type>
  </Table>
</Database>